apiVersion: apps/v1
kind: Deployment
metadata:
  name: tejas-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tejas-app
  template:
    metadata:
      labels:
        app: tejas-app
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: tejas-pv

      containers:
        - name: container-1
          image: us-central1-docker.pkg.dev/k8s-project-417119/k8-artifactregistry-container1/k8-container1:v2
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: tejas-pv
              mountPath: /tejas_PV_dir 

        - name: container-2
          image: us-central1-docker.pkg.dev/k8s-project-417119/k8-artifactregistry-container2/k8-container2:v2
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: tejas-pv
              mountPath: /tejas_PV_dir
            

