steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/k8s-project-417119/k8-artifactregistry-container2/k8-container2:v2', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/k8s-project-417119/k8-artifactregistry-container2/k8-container2:v2']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=./Manifest/
      - --image=us-central1-docker.pkg.dev/k8s-project-417119/k8-artifactregistry-container2/k8-container2:v2
      - --location=us-central1
      - --cluster=k8-cluster
